<script type="text/javascript" src="resources/js/jquery.min.js"></script>
<script type="text/javascript" src="resources/js/validacionpanel.js"></script>
<script type="text/javascript" src="resources/js/jquery-migrate.min.js"></script>
<script type="text/javascript" src="resources/js/bootstrap.min.js"></script>
<script type="text/javascript" src="resources/js/pgwslider.min.js"></script>
<script type="text/javascript" src="resources/js/back-to-top.min.js"></script>
<script type="text/javascript" src="resources/js/smoothScroll.min.js"></script>
<script type="text/javascript" src="resources/js/owl.carousel.min.js"></script>
<script type="text/javascript" src="resources/js/sequence.jquery-min.js"></script>
<script type="text/javascript" src="resources/js/greensock.js"></script>
<script type="text/javascript" src="resources/js/layerslider.transitions.js"></script>
<script type="text/javascript" src="resources/js/layerslider.kreaturamedia.jquery.js"></script>
<script type="text/javascript" src="resources/js/custom.min.js"></script>
<script type="text/javascript" src="resources/js/app.min.js"></script>
<script type="text/javascript" src="resources/js/owl-carousel.min.js"></script>
<script type="text/javascript" src="resources/js/datepicker.min.js"></script>
<script type="text/javascript" src="resources/js/validation.min.js"></script>
<script type="text/javascript" src="resources/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script type="text/javascript" src="resources/js/owl-recent-works.min.js"></script>
<script type="text/javascript" src="resources/js/wow.min.js"></script>
<script type="text/javascript" src="resources/js/ufps.js"></script>
